### ISSUE TITLE
Using my.cdash.org and the GitHub App - no status from CDash on warnings

### ISSUE THREAD

**Issue by bldrvnlw** [Kitware/CDash#1171]
In a GithubActions CI (see https://github.com/biovault/HDILib/actions/runs/1115799997) a static analysis job submits build results to my.cdash.org  (https://my.cdash.org/index.php?project=HDILib&date=2021-08-10) using CTest. As expected the dashboard has entries

The GitHub app from https://github.com/apps/my-cdash-org has been installed in the organization and the Project configured as per the instructions in https://blog.kitware.com/github-checks-and-statuses-from-cdash/. The project has a large number of warnings (50) which I though would product a status change on GitHub but this is not happening.

This gives rise to two questions:

1. Is it possible to treat warnings (or a number of warnings above a certain threshold) as errors for GitHub? 
2. How can I test that the CDash GitHub application settings are correct?

**Comment by zackgalbreath** [comment]
> Is it possible to treat warnings (or a number of warnings above a certain threshold) as errors for GitHub?

Unfortunately not. Posting a failing status check is [currently hardcoded for > 0 configure errors, build errors, or test failures](https://github.com/Kitware/CDash/blob/master/app/cdash/app/Lib/Repository/GitHub.php#L402). Would it be possible to turn on something like `-Werror` for your static analysis job?

> How can I test that the CDash GitHub application settings are correct?

Pass or fail, you should see CDash posting a status back to your commit on GitHub. To get this to work, you'll need to perform an "update step" in CTest so that CDash knows what commit is being tested (so it knows where to post the check).

Try adding the following to `CAnalysisBuild.cmake`, just before the call to `ctest_build(...)`.

```cmake
set(CTEST_UPDATE_VERSION_ONLY 1)
ctest_update()
```

**Comment by bldrvnlw** [comment]
Thanks @zackgalbreath!

Of course -Werror !- should have thought of that 😮🌴! Probably combined with GithubActions _continue-on-error: true_ and _/wdnnnn_ to filter out specific analysis warnings we decide are not applicable. I'll try that out.

Indeed the ctest_update was missing. Thanks again for your time...
