### ISSUE TITLE
How to display custom groups on the dashboard page?

### ISSUE THREAD

**Issue by bilke** [Kitware/CDash#1285]
I have created a new build group `master`. In CI on `master`-branch I submit to CDash via

```bash
ctest -M Experimental --group master -T Test -T Submit
```

It successfully submits:

```
Send to group: master
...
Submission successful
```

But the submitted job does not show on the dashboard and I cannot find it otherwise.

Are there any steps necessary to view custom build groups? Thanks a lot!

**Comment by zackgalbreath** [comment]
The steps you describe look good to me.

One gotcha I can think of is that you might have created your new group as "Latest" rather than "Daily".

"Latest" groups essentially copy their results from "Daily" groups with the distinction that they always show the most recent results, even if they occurred on a previous testing day. To define contents for a Latest group, you need to add builds under the Dynamic BuildGroups tab.

To make sure there's nothing wrong with submitting or viewing results on your CDash instance, the easiest thing to do is probably to delete your "master" build group and recreate it as type "Daily".

**Comment by bilke** [comment]
Thanks! It worked: after deleting the build group and re-creating it as type "Daily" the build now shows up!
