### ISSUE TITLE
Front page has active links to pages not populated yet

### ISSUE THREAD

**Issue by fedorov** [Kitware/CDash#175]
The issue is that a link corresponding to a certain build available on the CDash front page links to a page that does not have any links to the build details.

Example and details are available in this post for 3D Slicer project: http://slicer-devel.65872.n3.nabble.com/Problems-using-the-dashboard-interface-td4035621.html

**Comment by zackgalbreath** [comment]
Thanks for the report.  I believe that the problem you were experiencing may have been due to a bug that has since been fixed.  This bug occurred when selecting "All Items Per Page".  This would inadvertently cause no results to be displayed instead.

I just updated slicer.cdash.org, so please let me know if this problems still persists for you.  Note that your browser might have the old (bugged) Javascript file cached, so please do a full refresh.

**Comment by fedorov** [comment]
Thanks -- I will reopen if I see this problem again!
