### ISSUE TITLE
Revoke token not working v3.2.2

### ISSUE THREAD

**Issue by ELCapitanLLNL** [Kitware/CDash#1980]
# Bug report

### Expected Behavior

token disappear 

### Actual Behavior

revoked token shows again after logout/login

### CDash Version

3.2.2

### Additional Information

LGID

**Comment by williamjallen** [comment]
We're having trouble reproducing this issue.  If you are able to provide more information about what caused it, feel free to post it here and I will reopen the issue.  If you observe the issue again, you can check the site logs (typically stored in `cdash/storage/logs`, or output to stderr) and the browser console to see if there is more information about what the problem is.
