### ISSUE TITLE
API getbuildid returns result but with code 400

### ISSUE THREAD

**Issue by SpaceCyclist** [Kitware/CDash#2284]
# Bug report

### Expected Behavior

https://cdash.orfeo-toolbox.org/api/v1/getbuildid.php?project=OTB&site=ubuntu-20.04-llvm-xdk-full&stamp=20240613-1532-CI_Package&name=develop%20P-15576 should return 20X code with build id, not 400 (you may change url as job result can be deleted).

### Actual Behavior

Good job id but with HTTP code 400

### CDash Version

Not the last one (3.1) but it may be useful to signal the error.

### Additional Information

Check the HTTP code return with your web browser inspector

**Comment by williamjallen** [comment]
CDash 3.1 is pretty old at this point and is no longer receiving regular bug fixes.  A significant number of issues have been fixed since 3.1, so upgrading to a newer version of CDash will possibly resolve this issue.  If you continue to experience this error with a recent version of CDash, please file a new issue.
