### ISSUE TITLE
419 - Page expired on the installation

### ISSUE THREAD

**Issue by ITMaya** [Kitware/CDash#2380]
Hi,

I don't think this is a bug on Cdash' side but more an issue on my side. 

Everytime I'm trying start the installation of Cdash, I have a 419 - Page expired:
![image](https://github.com/user-attachments/assets/1dde9401-579a-48a5-9c95-c9db5c64be9b)

When I click on "Install":
![image](https://github.com/user-attachments/assets/2570f6ec-c5a2-4999-8be2-1e542d28db58)

Is it a session lifetime issue?

Thanks for your help

**Comment by williamjallen** [comment]
What version of CDash are you using?

**Comment by ITMaya** [comment]
Latest one: v3.4.0

**Comment by williamjallen** [comment]
This page was [removed](https://github.com/Kitware/CDash/pull/2279) in 3.5 because all of the functionality (and more) can be done via Artisan or configuration changes.  What are you trying to do with this page?  If you're trying to create a user, the command `php artisan user:save` is the best way to add new users.

**Comment by ITMaya** [comment]
Oh alright, I didn't know that. Thanks for the information, I think that's all I need to know, I will work with that.

Thanks again
