### ISSUE TITLE
Use a SQL query builder

### ISSUE THREAD

**Issue by jeffbaumes** [Kitware/CDash#283]
This is probably pretty obvious to people already, but building SQL strings manually seems scary to me. Using a SQL query builder (random Google result: [Laravel](https://laravel.com/docs/4.2/queries)) seems like it would make the code cleaner and safer (e.g. cleans strings for you).

**Comment by jamiesnape** [comment]
Doctrine would be the best option.

**Comment by zackgalbreath** [comment]
Since we're already using PDO, why not use [prepared statements](http://php.net/manual/en/pdo.prepared-statements.php)?

**Comment by jamiesnape** [comment]
That would solve the scariness problem.

**Comment by danlamanna** [comment]
@zackgalbreath Most query builders are pretty good at already using prepared statements.

It's been a while since I was in PHP land, but doctrine was the canonical ORM/Query builder back then. Laravel is huge now, and it looks like their builder (Eloquent) can be used without the framework, so my vote would be to look into those.

**Comment by cpatrick** [comment]
Doctrine would have my vote.

**Comment by jeffbaumes** [comment]
Anything over status quo would be excellent in my mind. Ideally it would be something you can just add as an available dependency and work through converting various files as they are encountered instead of requiring a one-time conversion of everything.

**Comment by jamiesnape** [comment]
Doctrine (or any other ORM) is not too bad. I used a tool a while back that could create all the entities automatically from the database (easier if the database has the correct foreign keys). After that you can gradually refactor the code.

**Comment by danlamanna** [comment]
It's a divisive issue, but worth discussing here. Do we want to use doctrine as an ORM, a query builder, or both? Right now it seems like CDash is in between using models as objects corresponding to rows, and just classes separating logic (Girder takes this approach using singletons for their models).

**Comment by williamjallen** [comment]
Closing this issue since it is mostly stale at this point...  We currently use Laravel, and the ultimate goal is to convert all of the queries to use Laravel's various database features.  All of the immediate "scariness" was fixed in https://github.com/Kitware/CDash/pull/1332, which converted most of the "scary" queries to use prepared statements.
