### ISSUE TITLE
Build Warnings In Dynamic Analysis Email Test

### ISSUE THREAD

**Issue by bryonbean** [Kitware/CDash#710]
https://github.com/Kitware/CDash/blob/290e23394a3ec638fb919f7f004afab78cdb62a8/tests/data/EmailProjectExample/cdash_3.log#L2-L27

@zackgalbreath Under what conditions is this email possible? It makes sense if the user has set their email preference to digest emails and as far as I can tell this should be the only condition under which an email with these contents is possible. Or is there some other requirement that I'm missing? If the email had not been previously sent for the build warnings then this would also be possible but that is where we run into a chicken and egg problem. If the build warnings exist it stands to reason that the user, without the digest preference set, has already received the email regarding the build warnings. Sound about right? Looks like this file has not changed in this regard so maybe its original test value has become obfuscated by time?

**Comment by zackgalbreath** [comment]
> @zackgalbreath Under what conditions is this email possible?

Haha, this was a tricky one.  Let me begin by saying that I don't think this is the ideal behavior.  It is simply the behavior that we currently have implemented.

There's three XML submissions for this build.
* First, Build.xml causes a "fixed build warnings" (category 8) email to be sent.
* Second, Test.xml causes a "fixed failing tests"  (category 10) email to be sent.
* Third, DynamicAnalysis.xml causes an error email to be sent out.  It makes sense that this email reports dynamic analysis errors (category 11), but it feels a little disingenuous to report (again) on the leftover warnings and test failures that didn't get fixed by this build (categories 3 and 5).

This would make sense if this project had "Email redundant failures" turned on, but it doesn't.
