### ISSUE TITLE
Issue with api/v1/getbuildid.php

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#742]
The following GET call is expected to return `1403578` but return `not found`:
http://slicer.cdash.org/api/v1/getbuildid.php?project=Slicer4&site=metroplex.kitware&stamp=20181018-0300-Nightly&name=27501-LesionSpotlight-git570ade1-g%2B%2B-64bits-Qt5.11-Release

**Comment by zackgalbreath** [comment]
This should be fixed now.  The build in the example you posted has since been deleted, but here's one that still exists:

http://slicer.cdash.org/api/v1/getbuildid.php?project=Slicer4&site=metroplex.kitware&stamp=20181024-0300-Extensions-4.10-Nightly&name=27501-LesionSpotlight-git570ade1-g%2B%2B-64bits-Qt5.11-Release

Please feel free to reopen this issue if the problem persists for you.
