### ISSUE TITLE
Build history is stuck to 2018-10-31

### ISSUE THREAD

**Issue by vlebourl** [Kitware/CDash#773]
Hi, 
We now are running CDash 2.6 prebuilt and it's going quite smoothly! We still have a minor issue though with the build history and build time graph being stuck at the end of October... Any reason why this is happening? How can we fix this?
Thanks in advance
Vincent

**Comment by vlebourl** [comment]
Yes and yes, but the old names are no longer in use at all. Any way to make CDash forget about the old names and use the new ones as its reference?

**Comment by sjoubert** [comment]
I've also observe this behavior on my setup for quite a while now (prebuilt_1e075408b6395bc97611b4d1845c8173fef32c37)

But this is not consistent and comes and go without any obvious trigger. I have multiple builds on my project, they are not all impacted at the same time and even among the ones having a stuck history, the last recorded date is not the same. And we did not have a build name change (at least not since the history stuck or in the days before).

**Comment by williamjallen** [comment]
Given how old this issue is, and the lack of reproducibility, it's hard to know whether this has been resolved.  Please create a new issue if you continue to observe this issue.
