### ISSUE TITLE
Supporting LLVM-COV SHOW instrumentation and coverage formats in CDASH

### ISSUE THREAD

**Issue by agouaillard-cosmo** [Kitware/CDash#859]
CDash (as far as I could find), only support gcov compatible format instead of the LLVM-COV instrumentation-based coverage format (see below).

Is there a plan to support the later? If not, can anyone point us in the right direction, and we would give it a try?

The llvm-cov show command shows line by line coverage of the binaries BIN,… using the profile data PROFILE. It can optionally be filtered to only show the coverage for the files listed in SOURCES.

""
To use _**llvm-cov show**_, you need a program that is compiled with instrumentation to emit profile and coverage data. To build such a program with clang use the _-fprofile-instr-generate_ and _-fcoverage-mapping_ flags. If linking with the clang driver, pass _-fprofile-instr-generate_ to the link stage to make sure the necessary runtime libraries are linked in.

The coverage information is stored in the built executable or library itself, and this is what you should pass to _**llvm-cov show**_ as a BIN argument. The profile data is generated by running this instrumented program normally. When the program exits it will write out a raw profile file, typically called _default.profraw_, which can be converted to a format that is suitable for the PROFILE argument using the _llvm-profdata_ merge tool.
""

**Comment by zackgalbreath** [comment]
CTest knows how to parse the following coverage formats:
* BlanketJS
* gcov
* cobertura
* codecov
* GTM
* mumps
* jacoco
* xdebug

CTest parses these various coverage formats and generates files in its own format called Coverage.xml and CoverageLog.xml. CDash knows how to read these.

More recently, we've decided to offload coverage parsing to CDash itself. So we upload raw coverage data to CDash rather than initially parsing it with CTest. The main reason for this change in approach is that when you add support for a new coverage format, you now only have to upgrade one thing (CDash) rather than the server & all the testing clients.

CDash itself currently knows how to parse:
* CTest coverage XML files
* tarballs of .gcov files (typically generated by this module)
* tarballs of JSCover files
* tarballs of Java JSON coverage files

That's a long-winded way of saying, I think you're right. We don't currently have a good way of parsing llvm-cov JSON files.

We're not opposed to adding support for this, but we don't currently have any plans to do so. Let me know if you're interested in giving this a try yourself, I'd be glad to give you some pointers on where to start.

**Comment by agouaillard-cosmo** [comment]
Thanks. I am interested in giving it a try. Can we set up a call? you can send me a calendar invite at agouaillard (at) gmail (dot) com.

**Comment by ericriff** [comment]
Has there been any development on this? 
We're looking into generating coverage reports with llvm and we would need this.

**Comment by zackgalbreath** [comment]
We don't currently have capacity to implement this feature request, but PRs are always welcome!

I'm not yet familiar with the type of output that `llvm-prodata` produces (presumably in "text" mode), but here's an example class that might be similar to what would need to be implemented for llvm-cov support:

https://github.com/Kitware/CDash/blob/master/app/cdash/xml_handlers/JSCoverTar_handler.php
