### ISSUE TITLE
unsafe javascript on my.cdash.org

### ISSUE THREAD

**Issue by jcfr** [Kitware/CDash#917]
This issue is similar to #761

Clicking on these icons fail:

![image](https://user-images.githubusercontent.com/219043/69458135-ad01da00-0d3c-11ea-9eb0-5186473b915d.png)

It redirects to:

```
unsafe:javascript:;
```

The "Colorblind palette" link has the same issue:

![image](https://user-images.githubusercontent.com/219043/69458191-d1f64d00-0d3c-11ea-8bb3-c3004d8cad3c.png)

**Comment by jcfr** [comment]
Cc: @bpaniagua

**Comment by agarcia-gmf** [comment]
I'm having the same issue: Firefox just rejects the navigation with:
`Prevented navigation to “unsafe:javascript:;” due to an unknown protocol.`
while Chromium tries to find an application to open the URL, finally causing an error:
`Could not find any application or handler for unsafe:javascript:;`

This makes it quite uncomfortable/messy to remove old build for instance.

**Comment by zackgalbreath** [comment]
Thanks for staying on top of this. It's fixed in master now. I'll update my.cdash.org soon.
