### ISSUE TITLE
Missing installation guide

### ISSUE THREAD

**Issue by tomasbrincil** [Kitware/CDash#955]
Hi there,
I am missing some instructions for sysadmins to install cdash without deeper knowledge of app itself. I tried to run git version but not sure if config is in the same place as mentioned in older installation guider or not. Should I run the http://localhost/install.php first? http://localhost/ is redirecting to non-existing http://localhost/viewProjects.php which ends with 404.
Thank you!

**Comment by aboualiaa** [comment]
Thumbs up on this one. Installing from docker also results in errors and there are no guides on how to set this up.

**Comment by zackgalbreath** [comment]
Thanks for pointing this out. I'll take another pass over our install docs soon.

**Comment by gemfony** [comment]
My +1 to this one, that's really necessary!
I was running the old version 2.0.x, and decided to restart from scratch with 2.6.0. However, i now can't get it running, lots of issues and guesswork. The Wiki information doesn't really help for 2.6.0.

How to get it running from scratch, using the zip release file. It should hint at the fact that both the PHP composer tool and nodejs + npm need to be installed, that is currently not mentioned anywhere. Mentioning as reference some "known working" Linux distributions and necessary OS packages would be nice also.

**Comment by aog2000a** [comment]
Thumbs up here also. It's really a pity... my impression is that several details which are not told anywhere would be enough to allow a reasonable user-install experience. As it is it is sadly a discouraging experience.

@zackgalbreath how to get the folder   "public/build"  generated and populated??
The command "npm run production" needs a "production" script which is nowhere to find...

**Comment by zackgalbreath** [comment]
This is still on my todo list. I'll try to get to it sooner rather than later. Thanks for your continued interest.

> how to get the folder "public/build" generated and populated??
> The command "npm run production" needs a "production" script which is nowhere to find...

This command is defined here:
https://github.com/Kitware/CDash/blob/master/package.json#L15

So running `npm run dev` (or development/prod/production) from the root of your CDash clone *should* work....

**Comment by aog2000a** [comment]
@zackgalbreath thanks, i see now, all that code is missing from the tarball 2.6.0... Perhaps it's worth doing a "stable point release" 2.6.1 which is tested to work from scratch, or writing some lines about how to handle that in https://public.kitware.com/Wiki/CDash:Installation

**Comment by emmenlau** [comment]
The new installation guide at https://github.com/Kitware/CDash/blob/master/docs/install.md is quite good. I think this issue can be closed? A few further details about installing 3.0.0 or newer are tracked in #1054 so this issue is mostly deprecated/superseded.

It may also be a good idea to remove https://public.kitware.com/Wiki/CDash:Installation at some point, to avoid confusion.

**Comment by aog2000a** [comment]
> It may also be a good idea to remove https://public.kitware.com/Wiki/CDash:Installation at some point, to avoid confusion.

Or just update to point it to the Github / tarball file... :-)

**Comment by emmenlau** [comment]
Sadly, I've found the wiki to be often quite outdated. I'm not sure whether a sparsely maintained wiki serves a good purpose. Since the wiki rates quite high in google search rankings, it basically kept me from finding the newer documentation on github. So I would consider removing it. But thats really just me...

**Comment by zackgalbreath** [comment]
Thanks for the suggestions. I've updated the installation guide on our wiki to merely point to the GitHub repo.
